# Generated by Django 4.2.8 on 2025-11-19 10:00

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveSmallIntegerField(help_text='Revision sequence number (1 = original submission)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='revision number')),
                ('response_to_reviewers', models.TextField(blank=True, help_text='Author response to reviewer comments', verbose_name='response to reviewers')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(help_text='User who created this revision', on_delete=django.db.models.deletion.PROTECT, related_name='revisions_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'revision',
                'verbose_name_plural': 'revisions',
                'db_table': 'revisions',
                'ordering': ['submission', '-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique submission identifier', primary_key=True, serialize=False)),
                ('title', models.TextField(help_text='Manuscript title', verbose_name='title')),
                ('abstract', models.TextField(help_text='Manuscript abstract', verbose_name='abstract')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('REVISION_NEEDED', 'Revision Needed'), ('REVISION_SUBMITTED', 'Revision Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', help_text='Current submission status', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When draft was created', verbose_name='created at')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, help_text='When manuscript was first submitted', null=True, verbose_name='submitted at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification time', verbose_name='updated at')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Full-text search index', null=True)),
                ('current_revision', models.ForeignKey(blank=True, help_text='Latest revision of this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.revision', verbose_name='current revision')),
                ('submitting_author', models.ForeignKey(help_text='User who submitted the manuscript', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='submitting author')),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='revision',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='submissions.submission', verbose_name='submission'),
        ),
        migrations.CreateModel(
            name='ManuscriptFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='S3 key or storage path', max_length=500, verbose_name='file path')),
                ('original_filename', models.CharField(help_text='Original uploaded filename', max_length=255, verbose_name='original filename')),
                ('file_type', models.CharField(choices=[('MANUSCRIPT', 'Manuscript Document'), ('COVER_LETTER', 'Cover Letter'), ('SUPPLEMENTARY', 'Supplementary Material'), ('FIGURE', 'Figure'), ('TABLE', 'Table'), ('REVISION', 'Revision Document'), ('RESPONSE', 'Response to Reviewers')], help_text='Type of manuscript file', max_length=20, verbose_name='file type')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes', verbose_name='file size')),
                ('mime_type', models.CharField(blank=True, help_text='File MIME type (e.g., application/pdf)', max_length=100, verbose_name='MIME type')),
                ('file_order', models.PositiveSmallIntegerField(default=1, help_text='Display order within file type', validators=[django.core.validators.MinValueValidator(1)], verbose_name='file order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='uploaded at')),
                ('revision', models.ForeignKey(help_text='Revision this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.revision', verbose_name='revision')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.submission', verbose_name='submission')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'manuscript file',
                'verbose_name_plural': 'manuscript files',
                'db_table': 'manuscript_files',
                'ordering': ['submission', 'revision', 'file_type', 'file_order'],
            },
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Author full name', max_length=255, verbose_name='full name')),
                ('email', models.EmailField(help_text='Author email address', max_length=254, verbose_name='email')),
                ('affiliation', models.CharField(blank=True, help_text='Author institutional affiliation', max_length=500, verbose_name='affiliation')),
                ('orcid_id', models.CharField(blank=True, help_text='Author ORCID identifier (e.g., 0000-0002-1825-0097)', max_length=19, verbose_name='ORCID iD')),
                ('is_corresponding', models.BooleanField(default=False, help_text='Whether this author is the corresponding author', verbose_name='is corresponding author')),
                ('author_order', models.PositiveSmallIntegerField(help_text='Author position in author list (1-based)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='author order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorship_set', to='submissions.submission', verbose_name='submission')),
                ('user', models.ForeignKey(blank=True, help_text='If author is a registered user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorships', to=settings.AUTH_USER_MODEL, verbose_name='registered user')),
            ],
            options={
                'verbose_name': 'authorship',
                'verbose_name_plural': 'authorships',
                'db_table': 'authorships',
                'ordering': ['submission', 'author_order'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitting_author', 'status'], name='sub_author_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', '-created_at'], name='sub_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-submitted_at'], name='sub_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='sub_search_vector_idx'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['submission', '-revision_number'], name='rev_sub_num_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revision',
            unique_together={('submission', 'revision_number')},
        ),
        migrations.AddIndex(
            model_name='manuscriptfile',
            index=models.Index(fields=['submission', 'revision'], name='file_sub_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='manuscriptfile',
            index=models.Index(fields=['file_type'], name='file_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='manuscriptfile',
            constraint=models.CheckConstraint(check=models.Q(('file_size__gt', 0)), name='file_size_positive'),
        ),
        migrations.AddIndex(
            model_name='authorship',
            index=models.Index(fields=['submission', 'author_order'], name='auth_sub_order_idx'),
        ),
        migrations.AddIndex(
            model_name='authorship',
            index=models.Index(fields=['email'], name='auth_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='authorship',
            constraint=models.CheckConstraint(check=models.Q(('author_order__gte', 1)), name='auth_order_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='authorship',
            unique_together={('submission', 'author_order')},
        ),
    ]
