# Generated by Django 4.2.8 on 2025-11-19 05:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Email address (used for login)', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('full_name', models.CharField(blank=True, help_text='User display name', max_length=255, verbose_name='full name')),
                ('orcid_id', models.CharField(blank=True, db_index=True, help_text='ORCID identifier (e.g., 0000-0002-1825-0097)', max_length=19, null=True, unique=True, verbose_name='ORCID iD')),
                ('orcid_access_token', models.CharField(blank=True, help_text='ORCID OAuth2 access token (encrypted in production)', max_length=500)),
                ('orcid_refresh_token', models.CharField(blank=True, help_text='ORCID OAuth2 refresh token (encrypted in production)', max_length=500)),
                ('orcid_token_expires_at', models.DateTimeField(blank=True, help_text='ORCID token expiration time', null=True)),
                ('affiliation', models.CharField(blank=True, help_text='Current institution/organization', max_length=255, verbose_name='affiliation')),
                ('bio', models.TextField(blank=True, help_text='Short biography or research interests', verbose_name='biography')),
                ('profile_picture_url', models.URLField(blank=True, help_text='URL to profile picture', verbose_name='profile picture')),
                ('role', models.CharField(choices=[('author', 'Author'), ('reviewer', 'Reviewer'), ('editor', 'Editor'), ('admin', 'Administrator')], db_index=True, default='author', help_text='User role in the system', max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin site.', verbose_name='staff status')),
                ('email_verified', models.BooleanField(default=False, help_text='Email verification status', verbose_name='email verified')),
                ('orcid_verified', models.BooleanField(default=False, help_text='ORCID verification status', verbose_name='ORCID verified')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, verbose_name='phone number')),
                ('country', models.CharField(blank=True, help_text='Country of residence', max_length=100, verbose_name='country')),
                ('research_interests', models.JSONField(blank=True, default=list, help_text='List of research interests/keywords', verbose_name='research interests')),
                ('expertise_areas', models.JSONField(blank=True, default=list, help_text='Areas of expertise for reviewing', verbose_name='expertise areas')),
                ('publications_count', models.IntegerField(default=0, help_text='Number of publications', verbose_name='publications count')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications', verbose_name='email notifications')),
                ('submission_updates', models.BooleanField(default=True, help_text='Notifications for submission status changes', verbose_name='submission updates')),
                ('review_reminders', models.BooleanField(default=True, help_text='Reminders for pending reviews', verbose_name='review reminders')),
                ('newsletter_subscription', models.BooleanField(default=False, help_text='Subscribe to newsletter', verbose_name='newsletter subscription')),
                ('public_profile', models.BooleanField(default=True, help_text='Make profile publicly visible', verbose_name='public profile')),
                ('show_email', models.BooleanField(default=False, help_text='Display email on public profile', verbose_name='show email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['orcid_id'], name='users_orcid_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'email'], name='users_active_email_idx'),
        ),
    ]
