# Generated by Django 4.2.8 on 2025-11-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Whether user has completed their profile', verbose_name='profile completed'),
        ),
    ]
